# NAS音乐管理
services:
  navidrome:
    image: mmhdavu55jr8wl.xuanyuan.run/deluan/navidrome:latest
    user: 1000:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_LOGLEVEL: info
    volumes:
      - /share/CACHEDEV1_DATA/Container/navidrome/data:/data
      - /share/CACHEDEV2_DATA/hliblack/广播剧:/music:ro
