version: "3"
services: 
  it-tools: 
    image: "mmhdavu55jr8wl.xuanyuan.run/corentinth/it-tools" 
    container_name: it-tools 
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports: 
      - "18080:80" 
    volumes: 
      - "/share/CACHEDEV1_DATA/Container/it-tools/data:/data"
